include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    missing_required_param: error
    missing_return: error
    todo: info
    # This silences the "Missing documentation" warning you saw earlier
    public_member_api_docs: ignore

linter:
  rules:
    # --- ADDITIONS (Strictness & Performance) ---
    - require_trailing_commas
    - prefer_final_locals
    - prefer_final_in_for_each
    - unawaited_futures
    - avoid_void_async
    
    # --- STYLE & CLEANUP ---
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_constructors_first
    - sized_box_for_whitespace
    - use_decorated_box
    # --- REMOVALS/DISABLES ---
    # We disable this here as well to be safe
    - public_member_api_docs: false 
    # Usually too verbose for internal apps
    - always_specify_types: false